# Generated by Django 4.2.4 on 2023-12-24 08:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_intervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.client'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='intervenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.intervenant'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
