# Generated by Django 4.2.4 on 2023-12-24 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_intervention_client_intervention_intervenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='client',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.client'),
        ),
    ]
