# Generated by Django 4.2.4 on 2023-12-24 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_intervention_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='intervenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.intervenant'),
        ),
    ]
